#undef TAPPING_TERM
#define TAPPING_TERM 251

#define PERMISSIVE_HOLD

#undef RGB_MATRIX_TIMEOUT
#define RGB_MATRIX_TIMEOUT 180000

#undef RGB_MATRIX_VAL_STEP
#define RGB_MATRIX_VAL_STEP 3

#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "LprK6/EeRKoG"
#define LAYER_STATE_8BIT

#define MOUSE_EXTENDED_REPORT
#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
#define AUTO_MOUSE_DEFAULT_LAYER 4
#define NAVIGATOR_SCROLL_DIVIDER 24
#define RGB_MATRIX_STARTUP_SPD 60

